# Generated by Django 4.2.2 on 2023-06-25 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_messages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 28, 31, 49992)),
        ),
    ]
